# Generated by Django 4.0.4 on 2022-05-02 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer_ramy', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='BikeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('opis', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('client', models.TextField()),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.bike')),
            ],
        ),
        migrations.AddField(
            model_name='bike',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.biketype'),
        ),
    ]
