# Generated by Django 4.0.4 on 2022-05-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildingmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='max_people_count',
            field=models.PositiveSmallIntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='people_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('room', 'date')},
        ),
    ]
