# Generated by Django 4.0.4 on 2022-05-22 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildingmanagement', '0002_room_max_people_count_alter_room_people_count_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('room', 'date', 'user')},
        ),
    ]
