# Generated by Django 4.0.4 on 2022-05-22 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildingmanagement', '0003_alter_reservation_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('room', 'date', 'user'), ('date', 'user')},
        ),
    ]
